<?php

namespace webd\clustering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-22 at 13:14:05.
 */
class GMeansTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var GMeans
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GMeans;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\clustering\GMeans::run
     */
    public function testRun() {
        $nd = new \webd\stats\NormalDistribution();

        $points = array();
        for ($i = 0; $i < 100; $i++) {
            $points[] = new RnPoint($nd->sample() + 9, $nd->sample() + 9);
            $points[] = new RnPoint($nd->sample() + 1, $nd->sample() + 1);
        }

        $gmeans = new GMeans();
        $gmeans->points = $points;
        $gmeans->run();
    }
    
    /**
     * @covers webd\clustering\GMeans::run
     */
    public function testRun2() {
        $nd1 = new \webd\stats\NormalDistribution(9, 0.1);
        $nd2 = new \webd\stats\NormalDistribution(9, 0.4);

        $points = array();
        for ($i = 0; $i < 100; $i++) {
            $points[] = new RnPoint($nd1->sample(), $nd2->sample());
        }

        $gmeans = new GMeans();
        $gmeans->points = $points;
        $gmeans->run();
        
        $this->assertEquals(
                array(9, 9),
                $gmeans->centers_found[0]->getValue(),
                "",
                0.5);
    }

}
