<?php

namespace webd\clustering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-22 at 09:38:07.
 */
class KMeansTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var KMeans
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new KMeans;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\clustering\KMeans::addCenter
     * @todo   Implement testAddCenter().
     */
    public function testAddCenter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\clustering\KMeans::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        $this->object->k = 2;
        $this->object->n = 10;
        
        $points = array(
            new RnPoint(array(1, 1)),
            new RnPoint(array(2, 2)),
            new RnPoint(array(2, 3))
        );
        
        $this->object->points = $points;
        
        $this->object->run();        
    }

}
