<?php

namespace webd\clustering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-22 at 11:12:27.
 */
class KMeansNICTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var KMeansNIC
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new KMeansNIC;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\clustering\KMeansNIC::addCenter
     * @todo   Implement testAddCenter().
     */
    public function testAddCenter() {
        $this->object->addCenter(new RnCenter(array(0,0)));
        $this->object->addCenter(new RnCenter(array(3,3)));
        
        $this->object->k = 2;
        $this->object->n = 10;
        
        $points = array(
            new RnPoint(array(1, 1)),
            new RnPoint(array(2, 2)),
            new RnPoint(array(2, 3))
        );
        $this->object->points = $points;
        
        $this->object->run();
        
        $this->assertEquals(
                array(1, 1),
                $this->object->centers[0]->getValue()
        );
        $this->assertEquals(
                array(2, 2.5),
                $this->object->centers[1]->getValue()
        );
    }
    
    

}
